name: dw_barbershop
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  asyncstate: ^2.0.2

  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.3
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
